#pragma config(Motor,  port2,           driveR,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           driveL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           scoop,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           shooter,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           feeder,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftX = 0;
int leftY = 0;
int rightY = 0;
int rightX = 0;
const bool on = true;
int thresh = 15;
int slope = 2.5;
int count = 1;

/************button*assignment*************\
| 1: arm (right joystick x-axis)           |
| 2: arm (right joystick y-axis)           |
| 3: drive (left joystick y-axis)          |
| 4: drive (left joystick x-axis)          |
| 5U: slow acceleration (minivan mode)     |
| 5D:                                      |
| 6U: can lift stablizer                   |
| 6D: manual shooter button                |
| 7L:                                      |
| 7U: shoot top row auto                   |
| 7R: shoot middle auto                    |
| 7D: shoot bottom row auto                |
| 8L: get manny auto                       |
| 8U: come back manny auto                 |
| 8R: get cans auto                        |
| 8D: come back w/ cans auto               |
\******************************************/

task drive()
{
	while(on)
	{
		motor[driveL] = leftX - leftY;
		motor[driveR] = leftX + leftY;

		if(vexRT[Btn8L])
		{
			if(leftY+leftX == 0)
			{
				motor[driveL] = 127;
				motor[driveR] = 10;
				wait1Msec(575);

				motor[driveL] = 80;
				motor[driveR] = -128;
				wait1Msec(1750);

				motor[driveL] = 127;
				motor[driveR] = 127;
				wait1Msec(850);

				motor[driveL] = -128;
				motor[driveR] = 127;
				wait1Msec(1250);

				motor[driveL] = 0;
				motor[driveR] = 0;
			}
			else
			{
				motor[driveL] = leftX - leftY;
				motor[driveR] = leftX + leftY;
			}
		}
	}
}

task autoManny()
{
	while(on)
	{
		if(vexRT[Btn8L])
		{
			count++;
			if(count == 1)
			{
				if(leftY+leftX == 0)
				{
					motor[driveL] = 127;
					motor[driveR] = 10;
					wait1Msec(575);

					motor[driveL] = 80;
					motor[driveR] = -128;
					wait1Msec(1750);

					motor[driveL] = 127;
					motor[driveR] = 127;
					wait1Msec(600);

					motor[driveL] = -128;
					motor[driveR] = 127;
					wait1Msec(1250);

					motor[driveL] = 0;
					motor[driveR] = 0;
				}
			}

			if(vexRT[Btn8U])
			{
				count++;
				if(count == 1)
				{
					if(leftY+leftX == 0)
					{

						motor[driveL] = 127;
						motor[driveR] = -128;
						wait1Msec(1500);

						motor[driveL] = -128;
						motor[driveR] = -128;
						wait1Msec(650);

						motor[driveL] = 127;
						motor[driveR] = -80;
						wait1Msec(2125);

						motor[driveL] = 0;
						motor[driveR] = 0;
					}
				}
			}
			else
			{
				motor[driveL] = leftX - leftY;
				motor[driveR] = leftX + leftY;
			}
		}
	}
}

task autoShooter()
{
	if(vexRT[Btn8U])
	{
		motor[driveL] = 30;
		motor[driveR] = -30;
		wait1Msec(3000);

		motor[driveL] = -63;
		motor[driveR] = 63;
		wait1Msec(180);

		motor[driveL] = 63;
		motor[driveR] = 20;
		wait1Msec(3750);

		motor[driveL] = -63;
		motor[driveR] = 90;
		wait1Msec(750);

		motor[driveL] = -63;
		motor[driveR] = 63;
		wait1Msec(180);

		motor[driveL] = 0;
		motor[driveR] = 0;
		{
			motor[scoop] = -63;
			wait1Msec(1000);

			motor[scoop] = 63;
			wait1Msec(1000);

			motor[shooter] = 127;
			wait1Msec(1000);
		}
	}
	else
	{
		motor[driveL] = leftX - leftY;
		motor[driveR] = leftX + leftY;
	}
}

task manipulator()
{
	while(on)
	{
		{
			if(vexRT[Btn5U])
			{
				motor[scoop] = 55;//keep the scoop up for cans
			}
			else
			{
				motor[scoop] = rightY + 40;
			}

			if(vexRT[Btn5D])
			{
				motor[shooter] = 127;
			}
			else
			{
				motor[shooter] = 0;
			}
		}
	}
}

task feed()
{
	while(on)
	{
		if(vexRT(SensorValue(limitSwitch) == 1))
		{
			motor[shooter] = 127; // shooter mootor
			motor[feeder] = 127; // index servo
			wait1Msec(100);
			motor[feeder] = 100;
			wait1Msec(100);
			motor[feeder] = 127;
		}
	}
}

task main()
{
	startTask(drive);
	startTask(manipulator);
	startTask(autoManny);
	startTask(autoShooter);
	startTask(feed);

	while(on)
	{
		rightX = vexRT(Ch1);
		if(abs(rightX)<thresh){
			rightX = 0;
		}
		rightY = vexRT(Ch2);
		if(abs(rightY)<thresh){
			rightY = 0;
		}
		leftY = vexRT(Ch3);
		if(abs(leftY)<thresh){
			leftY = 0;
		}
		leftX = vexRT(Ch4);
		if(abs(leftX)<thresh){
			leftX = 0;
		}
	}
}
